/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import { AlertCircle } from 'lucide-react'
import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import { Dialog } from '@/components/dialog'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'

import { CHANNEL_STATUS } from '../../constants'
import { buildChannelAbilityPreview } from '../../lib/ability-preview'
import { useChannels } from '../channels-provider'

const MODEL_PREVIEW_LIMIT = 100

type AbilityPreviewDialogProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function AbilityPreviewDialog(props: AbilityPreviewDialogProps) {
  const { t } = useTranslation()
  const { currentRow } = useChannels()
  const preview = useMemo(
    () => (currentRow ? buildChannelAbilityPreview(currentRow) : null),
    [currentRow]
  )

  if (!currentRow || !preview) return null

  const visibleModels = preview.models.slice(0, MODEL_PREVIEW_LIMIT)
  const statusLabel =
    currentRow.status === CHANNEL_STATUS.ENABLED ? t('Enabled') : t('Disabled')

  return (
    <Dialog
      open={props.open}
      onOpenChange={props.onOpenChange}
      title={t('Ability Preview')}
      description={t(
        'Preview the routing abilities generated by channel {{name}}.',
        { name: currentRow.name }
      )}
      contentHeight='min(36rem, calc(100vh - 14rem))'
      contentClassName='sm:max-w-3xl'
      bodyClassName='space-y-5'
      footer={
        <Button variant='outline' onClick={() => props.onOpenChange(false)}>
          {t('Close')}
        </Button>
      }
    >
      <div className='grid grid-cols-2 gap-x-4 gap-y-3 sm:grid-cols-5'>
        <PreviewMetric
          label={t('Generated Abilities')}
          value={preview.abilityCount.toLocaleString()}
        />
        <PreviewMetric
          label={t('Models')}
          value={preview.models.length.toLocaleString()}
        />
        <PreviewMetric
          label={t('Groups')}
          value={preview.groups.length.toLocaleString()}
        />
        <PreviewMetric
          label={t('Priority')}
          value={String(currentRow.priority ?? 0)}
        />
        <PreviewMetric
          label={t('Weight')}
          value={String(currentRow.weight ?? 0)}
        />
      </div>

      <Separator />

      <div className='space-y-2'>
        <div className='flex items-center justify-between gap-3'>
          <h3 className='text-sm font-medium'>{t('Configured Groups')}</h3>
          <Badge variant='outline'>{statusLabel}</Badge>
        </div>
        <div className='flex flex-wrap gap-1.5'>
          {preview.groups.map((group) => (
            <Badge key={group} variant='secondary'>
              {group}
            </Badge>
          ))}
        </div>
      </div>

      {preview.abilityCount === 0 ? (
        <Alert>
          <AlertCircle aria-hidden='true' />
          <AlertDescription>
            {t(
              'No abilities will be generated until both models and groups are configured.'
            )}
          </AlertDescription>
        </Alert>
      ) : (
        <>
          <p className='text-muted-foreground text-sm'>
            {t(
              'Each model is combined with every group to create one routing ability.'
            )}
          </p>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>{t('Requested Model')}</TableHead>
                <TableHead>{t('Upstream Model')}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {visibleModels.map((model) => (
                <TableRow key={model.requestedModel}>
                  <TableCell className='font-mono break-all whitespace-normal'>
                    {model.requestedModel}
                  </TableCell>
                  <TableCell className='font-mono break-all whitespace-normal'>
                    {model.upstreamModel}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
          {visibleModels.length < preview.models.length ? (
            <p className='text-muted-foreground text-xs'>
              {t('Showing {{visible}} of {{total}} models.', {
                visible: visibleModels.length,
                total: preview.models.length,
              })}
            </p>
          ) : null}
        </>
      )}
    </Dialog>
  )
}

function PreviewMetric(props: { label: string; value: string }) {
  return (
    <div className='min-w-0'>
      <div className='text-muted-foreground text-xs'>{props.label}</div>
      <div className='mt-1 truncate text-lg font-semibold tabular-nums'>
        {props.value}
      </div>
    </div>
  )
}
